# Generated by Django 5.2.3 on 2025-06-12 01:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID de Conversación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnownDesease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Enfermedad')),
                ('short_description_for_llm', models.TextField(help_text='Descripción concisa de los síntomas y características clave que el LLM usará para orientar al usuario.', verbose_name='Descripción Breve (para el LLM)')),
                ('common_symptoms_list', models.TextField(blank=True, help_text='Opcional. Lista de síntomas típicos, separados por comas o puntos y comas (ej: picazón, enrojecimiento, ampollas pequeñas). El LLM puede usar esto para complementar la descripción.', null=True, verbose_name='Lista de Síntomas Comunes')),
                ('key_questions_to_ask', models.TextField(blank=True, help_text='Opcional. Preguntas específicas que el bot podría hacer si sospecha esta enfermedad (además de las generales del prompt principal).', null=True, verbose_name='Preguntas Clave Específicas (Opcional)')),
                ('general_advice_non_medical', models.TextField(blank=True, help_text="Opcional. Consejos generales como 'evitar rascarse', 'mantener la zona limpia y seca', 'evitar irritantes conocidos'. NUNCA debe ser tratamiento médico.", null=True, verbose_name='Consejo General (No Médico - Opcional)')),
            ],
            options={
                'verbose_name': 'Enfermedad Conocida por el Bot',
                'verbose_name_plural': 'Enfermedades Conocidas por el Bot',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido del Mensaje')),
                ('is_bot', models.BooleanField(default=False, verbose_name='¿Es del Bot?')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Marca de Tiempo')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation', verbose_name='Conversación')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['timestamp'],
            },
        ),
    ]
