# Generated by Django 5.2.3 on 2025-06-16 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Abreviatura (Ej: salida CNN)')),
                ('name_desease', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Enfermedad')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción General (Opcional)')),
                ('short_description_for_llm', models.TextField(help_text="Máx 5-15 palabras clave. Ej: 'Acné: Granos, espinillas. Cara/pecho/espalda.'", verbose_name='Descripción Breve para LLM (MUY CONCISA)')),
                ('cnn_prediction_index', models.IntegerField(blank=True, help_text='El índice numérico (0, 1, ...) que tu CNN devuelve para esta enfermedad.', null=True, unique=True, verbose_name='Índice de Predicción CNN (si aplica)')),
                ('common_symptoms_list', models.TextField(blank=True, help_text='Síntomas típicos, separados por comas.', null=True, verbose_name='Lista de Síntomas Comunes (Opcional)')),
                ('key_questions_to_ask', models.TextField(blank=True, help_text='Preguntas que el bot podría hacer si sospecha esta enfermedad.', null=True, verbose_name='Preguntas Clave Específicas (Opcional)')),
                ('general_advice_non_medical', models.TextField(blank=True, help_text='Consejos generales (no tratamiento).', null=True, verbose_name='Consejo General No Médico (Opcional)')),
            ],
            options={
                'verbose_name': 'Enfermedad (Base de Conocimiento)',
                'verbose_name_plural': 'Enfermedades (Base de Conocimiento)',
                'ordering': ['name_desease'],
            },
        ),
        migrations.DeleteModel(
            name='KnownDesease',
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Conversación del Chatbot', 'verbose_name_plural': 'Conversaciones del Chatbot'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp'], 'verbose_name': 'Mensaje de Chat', 'verbose_name_plural': 'Mensajes de Chat'},
        ),
        migrations.AddField(
            model_name='message',
            name='cnn_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Confianza CNN (%)'),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chatbot_images/', verbose_name='Imagen Adjunta (Opcional)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido del Mensaje de Texto'),
        ),
        migrations.AddField(
            model_name='message',
            name='cnn_predicted_desease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.desease', verbose_name='Enfermedad Sugerida por CNN (Opcional)'),
        ),
    ]
