# Generated by Django 5.2.3 on 2025-06-20 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_desease_delete_knowndesease_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSummary',
            fields=[
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='medical_summary', serialize=False, to='chatbot.conversation', verbose_name='Conversación Asociada')),
                ('summary_text_generated_by_llm', models.TextField(blank=True, help_text='Texto completo del resumen estructurado generado por el LLM.', null=True, verbose_name='Resumen de Ficha Preliminar (Generado por IA)')),
                ('main_complaint', models.TextField(blank=True, null=True, verbose_name='Motivo Principal de Consulta')),
                ('symptoms_reported', models.TextField(blank=True, null=True, verbose_name='Síntomas Reportados')),
                ('location_of_symptoms', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localización de Síntomas')),
                ('duration_of_symptoms', models.CharField(blank=True, max_length=255, null=True, verbose_name='Duración de Síntomas')),
                ('aggravating_factors', models.TextField(blank=True, null=True, verbose_name='Factores Agravantes')),
                ('alleviating_factors', models.TextField(blank=True, null=True, verbose_name='Factores de Alivio')),
                ('previous_history', models.TextField(blank=True, null=True, verbose_name='Antecedentes Relevantes')),
                ('image_analysis_summary_from_cnn', models.TextField(blank=True, null=True, verbose_name='Resumen del Análisis de Imagen (CNN)')),
                ('tentative_orientation_by_llm', models.TextField(blank=True, null=True, verbose_name='Orientación Tentativa del LLM (Texto)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización del Resumen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación del Resumen')),
            ],
            options={
                'verbose_name': 'Resumen de Conversación (Ficha Preliminar IA)',
                'verbose_name_plural': 'Resúmenes de Conversación (Fichas Preliminares IA)',
                'ordering': ['-created_at'],
            },
        ),
    ]
